# a very minimal declarative config file
_format_version: "2.1"
_transform: true
services:
  - name: user-server # name of service 2
    url: http://172.0.0.1:3001
    routes:
      - name: users
        paths:
          - /users