import {Prop} from '@nestjs/mongoose';
import {DatabaseBaseEntityAbstract} from '../../base/database.base.entity.abstract';
import {DatabaseDefaultUUID} from '../../../constants/database.function.constant';

/**
 * Abstract class `DatabaseMongoEntityAbstract` implements {@link DatabaseBaseEntityAbstract} with a string type parameter.
 * This class is used as a base for entities in a MongoDB database.
 *
 * @property {string} _id - The unique identifier for the entity. It is a string and its default value is generated by `DatabaseDefaultUUID`.
 */
export abstract class DatabaseMongoEntityAbstract implements DatabaseBaseEntityAbstract<string> {
    @Prop({
        type: String,
        default: DatabaseDefaultUUID,
    })
    _id: string;
}
