import {DatabaseBaseAuditedEntityAbstract} from '../../base/database.base.audited-entity.abstract';
import {Prop} from '@nestjs/mongoose';
import {DatabaseDefaultUUID} from '../../../constants/database.function.constant';
import {
    DATABASE_CREATED_AT_FIELD_NAME,
    DATABASE_CREATED_BY_USER_ID_FIELD_NAME,
    DATABASE_LAST_MODIFICATION_TIME_FIELD_NAME,
    DATABASE_LAST_MODIFIER_USER_ID_FIELD_NAME,
} from '../../../constants/database-fields.constant';

/**
 * Abstract class `DatabaseMongoAuditedEntityAbstract` extends {@link DatabaseBaseAuditedEntityAbstract} with a string type parameter.
 * This class is used as a base for entities that require auditing in a MongoDB database.
 *
 * @property {string} _id - The unique identifier for the entity. It is a string and its default value is generated by `DatabaseDefaultUUID`.
 *
 * @property {Date} DATABASE_CREATED_AT_FIELD_NAME - The date when the entity was created. It is a Date object and its default value is the current date and time.
 *
 * @property {string} DATABASE_CREATED_BY_USER_ID_FIELD_NAME - The identifier of the user who created the entity. It is a string and its default value is null.
 *
 * @property {Date} DATABASE_LAST_MODIFICATION_TIME_FIELD_NAME - The date when the entity was last modified. It is a Date object and its default value is null.
 *
 * @property {string} DATABASE_LAST_MODIFIER_USER_ID_FIELD_NAME - The identifier of the user who last modified the entity. It is a string and its default value is null.
 */
export abstract class DatabaseMongoAuditedEntityAbstract extends DatabaseBaseAuditedEntityAbstract<string> {
    @Prop({
        type: String,
        default: DatabaseDefaultUUID,
    })
    _id: string;

    @Prop({type: Date, default: Date.now})
    [DATABASE_CREATED_AT_FIELD_NAME]: Date;

    @Prop({type: String, default: null})
    [DATABASE_CREATED_BY_USER_ID_FIELD_NAME]: string;

    @Prop({type: Date, default: null})
    [DATABASE_LAST_MODIFICATION_TIME_FIELD_NAME]?: Date;

    @Prop({type: String, default: null})
    [DATABASE_LAST_MODIFIER_USER_ID_FIELD_NAME]: string;
}