export enum MintedEntityStatus {
    ALL = 'ALL',
    PENDING = 'PENDING',
    MERCHANT_REVIEW = 'MERCHANT_REVIEW',
    ADMIN_REVIEW = 'ADMIN_REVIEW',
    MINTED = 'MINTED',
    LISTED = 'LISTED',
    UNLISTED = 'UNLISTED',
}